version: "3.8"
services:
  backend:
    image: node:20-alpine
    container_name: backend
    volumes:
      - ./backend:/backend
    ports:
      - 3000:3000
    working_dir: /backend
    command: npm run setup
    tty: true

  frontend:
    image: node:20-alpine
    container_name: frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - 5173:5173
    working_dir: /frontend
    tty: true
    command: npm run setup
    depends_on:
      - backend
